apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.metadata.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.hpa.scaleTargetRef.kind }}
    name: {{ .Values.hpa.scaleTargetRef.name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.resources.limits.cpu }}
      targetAverageUtilization:  {{ .Values.resources.targetAverageUtilization }}
  - type: Resource
    resource:
      name: {{ .Values.resources.limits.memory }}
      targetAverageUtilization: {{ .Values.resources.targetAverageUtilization }}
